version: '3.9'

services:
  web:
    build: .
    ports: 
      - "80:80"
    environment:
      DATABASE_URI: ${DATABASE_URI}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
  grafana:
    image: grafana/grafana:5.2.4
    depends_on:
      - prometheus
    ports:
      - 3000:3000/tcp
    volumes:
      - ./grafana_db:/var/lib/grafana
    user: "104"

  prometheus:
    image: prom/prometheus:v2.4.3
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - 9090:9090/tcp
    depends_on:
      - redis
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
volumes:
  db-data: