---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-order-prefix
spec:
  stripPrefix:
    prefixes:
      - /order
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: default-routes
spec:
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      services:
        - name: auth-service
          namespace: default
          port: 80
    - kind: Rule
      match: PathPrefix(`/order`)
      priority: 2
      services:
        - name: order-chart-service
          namespace: default
          port: 80
      middlewares:
        - name: strip-order-prefix # Убираем префикс из пути, чтобы запросы шли на корень сервиса
          namespace: default