replicaCount: 2

image:
  repository: abramovku/crudapp
  version: "2.6"

app:
  port: 80
  port_name: http

service:
  type: ClusterIP
  port: 80
  port_name: web

ingress:
  host: arch.homework

postgresql:
  enabled: true
  auth:
    username: kirilluser
    password: passwd
    database: kirillapp
  service:
    ports:
      postgresql: "5432"

metrics:
  serviceMonitor:
    enabled: false