apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crudapp-chart.fullname" . }}
  labels:
    {{- include "crudapp-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "crudapp-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "crudapp-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
            - name: {{ .Values.app.port_name }}
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          env:
            - name: GREETINGS
              valueFrom:
                configMapKeyRef:
                  name: crudapp-config
                  key: GREETINGS
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: crudapp-secret
                  key: DATABASE_URI
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: crudapp-secret
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crudapp-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: crudapp-secret
                  key: POSTGRES_USER
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    {{- include "crudapp-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port_name }}
      protocol: TCP
      name: {{ .Values.service.port_name }}
  selector:
    {{- include "crudapp-chart.selectorLabels" . | nindent 4 }}