apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudapp-deployment
  labels:
    app: crudapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crudapp
  template:
    metadata:
      labels:
        app: crudapp    
    spec:
      containers:
        - name: crudapp-container
          image: abramovku/crudapp:1.4
          ports:
            - name: web
              containerPort: 80
          env:
              - name: GREETINGS
                valueFrom:
                  configMapKeyRef:
                    name: crudapp-config
                    key: GREETINGS
              - name: DATABASE_URI
                valueFrom:
                  secretKeyRef:
                    name: crudapp-secret
                    key: DATABASE_URI
              - name: POSTGRES_DB
                valueFrom:
                  secretKeyRef:
                    name: crudapp-secret
                    key: POSTGRES_DB
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: crudapp-secret
                    key: POSTGRES_PASSWORD
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: crudapp-secret
                    key: POSTGRES_USER

---
apiVersion: v1
kind: Service
metadata:
  name: crudapp-service
spec:
  selector:
    app: crudapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: web
  type: NodePort