apiVersion: v1
kind: Secret
metadata:
  name: crudapp-secret
type: Opaque
data:
  DATABASE_URI: cGdzcWw6aG9zdD1wb3N0Z3Jlcztwb3J0PTU0MzI7ZGJuYW1lPW15YXBwOwo=
  POSTGRES_DB: bXlhcHAK
  POSTGRES_PASSWORD: cGFzc3dkCg==
  POSTGRES_USER: bXl1c2VyCg==