apiVersion: v1
kind: Secret
metadata:
  name: crudapp-secret
type: Opaque
data:
  DATABASE_URI: cGdzcWw6aG9zdD1kYXRhYmFzZTtwb3J0PTU0MzI7ZGJuYW1lPW15YXBwOw==
  POSTGRES_DB: bXlhcHA=
  POSTGRES_PASSWORD: cGFzc3dk
  POSTGRES_USER: bXl1c2Vy