apiVersion: v1
kind: Secret
metadata:
  name: crudapp-secret
type: Opaque
data:
  DATABASE_URI: cGdzcWw6aG9zdD1wb3N0Z3Jlcztwb3J0PTU0MzI7ZGJuYW1lPWtpcmlsbGFwcDs=
  POSTGRES_DB: a2lyaWxsYXBw
  POSTGRES_PASSWORD: cGFzc3dk
  POSTGRES_USER: a2lyaWxsdXNlcg==