version: '3.9'

services:
  web:
    build: .
    ports: 
      - "80:80"
    environment:
      DATABASE_URI: ${DATABASE_URI}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      JWT_SECRET: ${JWT_SECRET}