apiVersion: v1
kind: ConfigMap
metadata:
  name: crudapp-config
data:
  GREETINGS: "Horray"
---
apiVersion: v1
kind: Secret
metadata:
  name: crudapp-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "pgsql:host=%s;port=%s;dbname=%s;" (include "postgresql.fullname" .) .Values.postgresql.service.ports.postgresql .Values.postgresql.auth.database | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}