apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  JWT_SECRET: {{ .Values.jwt.secret | b64enc | quote }}
  DATABASE_URI: {{ printf "pgsql:host=%s;port=%s;dbname=%s;" (include "postgresql.fullname" .) .Values.postgresql.service.ports.postgresql .Values.postgresql.auth.database | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}